apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata: # kpt-merge: default/intent1-junos
  name: intent1-junos
  namespace: default
  labels:
    config.sdcio.dev/targetName: junos-central
    config.sdcio.dev/targetNamespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.sdcio.dev|Config|default|intent1-junos'
spec:
  priority: 10
  config:
  - path: /
    value:
      configuration:
        vlans:
          vlan:
          - name: VLAN102
            vlan-id: 102
            l3-interface: irb.102
          - name: VLAN104
            vlan-id: 104
            l3-interface: irb.104
          - name: VLAN105
            vlan-id: 105
            l3-interface: irb.105
          - name: VLAN106
            vlan-id: 106
            l3-interface: irb.106
          - name: VLAN107
            vlan-id: 107
            l3-interface: irb.107
          - name: VLAN108
            vlan-id: 108
            l3-interface: irb.108
          - name: VLAN109
            vlan-id: 109
            l3-interface: irb.109
          - name: VLAN110
            vlan-id: 110
            l3-interface: irb.110
        interfaces:
          interface:
          - name: irb
            unit:
            - name: "102"
              family:
                inet:
                  address:
                  - name: "192.168.51.3/24"
            - name: "104"
              family:
                inet:
                  address:
                  - name: "192.168.53.3/24"
            - name: "105"
              family:
                inet:
                  address:
                  - name: "192.168.54.4/24"
            - name: "106"
              family:
                inet:
                  address:
                  - name: "192.168.55.3/24"
            - name: "107"
              family:
                inet:
                  address:
                  - name: "192.168.56.3/24"
            - name: "108"
              family:
                inet:
                  address:
                  - name: "192.168.57.3/24"
            - name: "109"
              family:
                inet:
                  address:
                  - name: "192.168.58.3/24"
            - name: "110"
              family:
                inet:
                  address:
                  - name: "192.168.59.3/24"
          - name: ge-0/0/1
            unit:
            - name: "0"
              family:
                ethernet-switching:
                  interface-mode: trunk
                  vlan:
                  - members:
                    - VLAN102
                    - VLAN104
                    - VLAN105
                    - VLAN106
                    - VLAN107
                    - VLAN108
                    - VLAN109
                    - VLAN110
        routing-instances:
          instance:
          - name: n2
            instance-type: vrf
            interface:
            - name: irb.106
            - name: irb.110
            route-distinguisher:
              rd-type: "100:1"
            vrf-target:
              community: "target:100:1"
            protocols:
              bgp:
                group:
                - name: internal
                  type: internal
                  local-as:
                    as-number: 65002
                  neighbor:
                  - name: 192.168.55.1
                    peer-as: 65002
                  - name: 192.168.59.1
                    peer-as: 65002
          - name: n4
            instance-type: vrf
            interface:
            - name: irb.102
            - name: irb.107
            route-distinguisher:
              rd-type: "100:2"
            vrf-target:
              community: "target:100:2"
            protocols:
              bgp:
                group:
                - name: internal
                  type: internal
                  local-as:
                    as-number: 65004
                  neighbor:
                  - name: 192.168.51.1
                    peer-as: 65004
                  - name: 192.168.56.1
                    peer-as: 65004
          - name: e1
            instance-type: vrf
            interface:
            - name: irb.104
            - name: irb.108
            route-distinguisher:
              rd-type: "100:3"
            vrf-target:
              community: "target:100:3"
            protocols:
              bgp:
                group:
                - name: internal
                  type: internal
                  local-as:
                    as-number: 65001
                  neighbor:
                  - name: 192.168.53.1
                    peer-as: 65001
                  - name: 192.168.57.1
                    peer-as: 65001
          - name: f1
            instance-type: vrf
            interface:
            - name: irb.105
            - name: irb.109
            route-distinguisher:
              rd-type: "100:4"
            vrf-target:
              community: "target:100:4"
            protocols:
              bgp:
                group:
                - name: internal
                  type: internal
                  local-as:
                    as-number: 65005
                  neighbor:
                  - name: 192.168.54.1
                    peer-as: 65005
                  - name: 192.168.58.1
                    peer-as: 65005
