apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata: # kpt-merge: k0smotron/CLUSTER_NAME
  name: CLUSTER_NAME
  namespace: k0smotron
  annotations:
    internal.kpt.dev/upstream-identifier: 'k0smotron.io|Cluster|k0smotron|CLUSTER_NAME'
spec:
  k0sVersion: k0s_Release_Version # kpt-set: ${k0s-release-version}
  persistence:
    type: emptyDir
  service:
    type: LoadBalancer
