apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata: # kpt-merge: NAME_SPACE/CLUSTER_NAME
  name: CLUSTER_NAME
  namespace: NAME_SPACE # kpt-set: ${k0s-cluster-ns}
  annotations:
    internal.kpt.dev/upstream-identifier: 'k0smotron.io|Cluster|NAME_SPACE|CLUSTER_NAME'
spec:
  version: k0s_Release_Version # kpt-set: ${k0s-release-version}
  persistence:
    type: emptyDir
  service:
    type: LoadBalancer
